export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const CONFIRM_CODE_START = 'CONFIRM_CODE_START';
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_FAILURE = 'CONFIRM_CODE_FAILURE';
