export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const CONFIRM_CODE_START = 'CONFIRM_CODE_START';
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_FAILURE = 'CONFIRM_CODE_FAILURE';
export const CLEAR_REDUX_DATA = 'CLEAR_REDUX_DATA';
export const ADDRESS_SELECTED = 'ADDRESS_SELECTED';
export const APPEND_PRODUCTS = 'APPEND_PRODUCTS';
export const SET_CATEGORY_PRODUCTS_PAGE = 'SET_CATEGORY_PRODUCTS_PAGE';
export const SET_ADDING_PRODUCT_TO_CART = 'SET_ADDING_PRODUCT_TO_CART';
export const CLEAR_ADDING_PRODUCT_TO_CART = 'CLEAR_ADDING_PRODUCT_TO_CART';
export const ADD_PRODUCT_TOCART_ERROR = 'ADD_PRODUCT_TOCART_ERROR';
export const UPDATE_CART_ITEM_IMMEDIATELY = 'UPDATE_CART_ITEM_IMMEDIATELY';
export const APPEND_SEARCH_PRODUCTS = 'APPEND_SEARCH_PRODUCTS';
export const SET_SEARCH_PRODUCTS_PAGE = 'SET_SEARCH_PRODUCTS_PAGE';
export const START_FETCHING_CATEGORY_PRODUCTS =
  'START_FETCHING_CATEGORY_PRODUCTS';
export const STOP_FETCHING_CATEGORY_PRODUCTS =
  'START_FETCHING_CATEGORY_PRODUCTS';
